<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.oracle.com/bpel/workflow/taskQueryService"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:taskError="http://xmlns.oracle.com/bpel/workflow/taskError"
                xmlns:tsc="http://xmlns.oracle.com/bpel/workflow/common/tsc"
                xmlns:common="http://xmlns.oracle.com/bpel/workflow/common"
                xmlns:ns0="http://xmlns.oracle.com/bpel/workflow/TaskEvidenceService"
                xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
                xmlns:query="http://xmlns.oracle.com/bpel/workflow/taskQuery"
                xmlns:task="http://xmlns.oracle.com/bpel/workflow/task">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source/>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="WSDLs/XMLSchema_-210786719.xsd"/>
        <oracle-xsl-mapper:rootElement name="taskListRequest"
                                       namespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140510.0600.0187) AT [TUE JUL 08 14:57:03 EST 2014].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="username"/>
  <xsl:param name="password"/>
  <xsl:template match="/">
    <tns:taskListRequest>
      <common:workflowContext>
        <common:credential>
          <common:login>
            <xsl:value-of select="$username"/>
          </common:login>
          <common:password>
            <xsl:value-of select="$password"/>
          </common:password>
        </common:credential>
      </common:workflowContext>
      <query:taskPredicateQuery startRow="1" endRow="10">
        <query:predicate>
          <query:assignmentFilter>All</query:assignmentFilter>
        </query:predicate>
      </query:taskPredicateQuery>
    </tns:taskListRequest>
  </xsl:template>
</xsl:stylesheet>
