<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://www.example.org/TaskListResponse"
                xmlns:ns0="http://xmlns.oracle.com/bpel/workflow/taskQueryService"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:taskError="http://xmlns.oracle.com/bpel/workflow/taskError"
                xmlns:tsc="http://xmlns.oracle.com/bpel/workflow/common/tsc"
                xmlns:common="http://xmlns.oracle.com/bpel/workflow/common"
                xmlns:ns1="http://xmlns.oracle.com/bpel/workflow/TaskEvidenceService"
                xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
                xmlns:query="http://xmlns.oracle.com/bpel/workflow/taskQuery"
                xmlns:task="http://xmlns.oracle.com/bpel/workflow/task">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="WSDLs/XMLSchema_-210786719.xsd"/>
        <oracle-xsl-mapper:rootElement name="taskListResponse"
                                       namespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="WSDLs/TaskListResponse.xsd"/>
        <oracle-xsl-mapper:rootElement name="taskListResponse" namespace="http://www.example.org/TaskListResponse"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140510.0600.0187) AT [TUE JUL 08 14:38:35 EST 2014].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:taskListResponse>
      <xsl:for-each select="/ns0:taskListResponse/task:task">
        <tns:task>
          <tns:title>
            <xsl:value-of select="task:title"/>
          </tns:title>
          <tns:taskId>
            <xsl:value-of select="task:systemAttributes/task:taskId"/>
          </tns:taskId>
        </tns:task>
      </xsl:for-each>
    </tns:taskListResponse>
  </xsl:template>
</xsl:stylesheet>
